Description: sitestack.cloud release hosting
Resources:

  # IAM USERS ##################################################################

  Publisher:
    Type: AWS::IAM::User
    Properties:
      Policies:
        - PolicyName: Publish
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Action: s3:ListBucket
                Effect: Allow
                Resource:
                  Fn::Sub: arn:aws:s3:::${Bucket}
              - Action:
                  - s3:DeleteObject
                  - s3:GetObject
                  - s3:PutObject
                Effect: Allow
                Resource:
                  Fn::Sub: arn:aws:s3:::${Bucket}/*

  # S3 #########################################################################

  Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: releases.sitestack.cloud
